---
title: "Direct standardization of mortality rates"
author: "Steve Simon"
source: new
date: "2021-09-20"
categories:
- Blog post
tags:
- Epidemiology
- Incomplete pages
- Rmarkdown graphs
output: html_document
page_update: complete
---

Mortality rates in different regions of the United States between different countries are dependent on the demographic distributions. Differences in the age distribution can cause mortality rates that are actually equivalent to appear as if they differ. These differences could just as easily hide a difference in mortality rates between two regions or even make the difference go in the opposite direction. Direct standardization is a simple approach to adjust mortality rates 

```{r direct-standardization-01}
suppressMessages(suppressWarnings(library(broom)))
suppressMessages(suppressWarnings(library(dplyr)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(magrittr)))
```

<!---More--->

### References

Omar B. Ahmad, Cynthia Boschi-Pinto, Alan D. Lopez, Christopher JL Murray, Rafael Lozano, Mie Inoue. Age standardization of rates: A new WHO standard. GPE Discussion Paper Series: No.31, World Health Organization 2001. Available in [pdf format][who1].


[who1]: https://www.who.int/healthinfo/paper31.pdf?ua=1
