---
title: "Check links between old and new pages"
author: "Steve Simon"
date: "Created 2022-05-26"
output: html_document
---

### Setup

```{r setup, echo=TRUE}
knitr::opts_chunk$set(echo=TRUE)
suppressMessages(suppressWarnings(library(glue)))
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(lubridate)))
suppressMessages(suppressWarnings(library(tidyverse)))
```

### Read html files

```{r read_old}
html_path <- "c:/Users/steve/Dropbox/professional/fun stuff/update-website/"
# html_path <- "c:/Users/simons/Dropbox/professional/fun stuff/update-website/"
html_pattern <- "html$"
md_path <- "../text/"
md_pattern <- "md$"
subdir_list=c("99", paste0("0", 0:9), 10:22)
md_files <- NULL
html_files <- NULL
for (yr in rev(subdir_list)) {
  print(yr)

  file_path <- paste0(md_path, yr)
  file_path %>%
    list.files(pattern="md$") %>%
    data.frame(yr=yr, fn=.) %>%
    bind_rows(md_files) -> md_files

  file_path <- paste0(html_path, yr)
  list.files(file_path, pattern="html$") -> yr_files
  if (length(yr_files)==0) next
  html_files <- bind_rows(
    data.frame(yr=yr, fn=yr_files),
    html_files)
}
```

### Read html files

```{r read_html}
path_prefix <- "c:/Users"
path_suffix <- "dropbox/professional/fun stuff/update-website"

list.files(path_prefix) %>%
  str_subset("(Simons)|(steve)") -> me

full_path <- glue("{path_prefix}/{me}/{path_suffix}")

print(glue("Searching in {full_path}"))

list.files(full_path)


subdir_list=c("99", paste0("0", 0:9), 10:22)
html_files <- NULL
for (yr in subdir_list) {
  file_path <- glue("{full_path}/{yr}")
  list.files(file_path, pattern="html$") -> yr_files
  if (length(yr_files)==0) next
  html_files <- bind_rows(
    data.frame(yr=yr, fn=yr_files),
    html_files)
}
count(html_files, yr)
```

### Read md files

```{r read_md}
md_path <- "../text/"
subdir_list=c("99", paste0("0", 0:9), 10:22)
md_files <- NULL
for (yr in rev(subdir_list)) {
  file_path <- paste0(md_path, yr)
  file_path %>%
    list.files(pattern="md$") %>%
    data.frame(yr=yr, fn=.) %>%
    bind_rows(md_files) -> md_files
}
count(md_files, yr)
```

### List duplicates

```{r list-duplicates}
md_files %>%
  group_by(fn) %>%
  mutate(n=n()) %>%
  filter(n>1) %>%
  select(-n) %>%
  arrange(fn, yr) %>%
  data.frame
html_files %>% count(yr)
```

Next step, search for 
+ [sim1]: http://www.pmean.com/??/...
+ <p>This page has moved to <a href="http://new.pmean.com/.../">a new website</a>.</p>

### Links found in md files

```{r md_links}
sim1 <- "[sim1]: http://www.pmean.com/"
full_file_name <- glue("{full_path}/{md_files$yr}/{md_files$fn}")
md_links <- NULL
for (i_fn in full_file_name) {
  read_lines(i_fn) %>%
    str_subset(fixed(sim1)) %>%
    str_replace(fixed(sim1), "") -> md_link
  md_link <- ifelse(length(md_link>0), md_link[1], "No link")
  md_file <- str_replace(i_fn, md_path, "")
  md_year <- str_sub(md_file, 1, 2)
  md_file <- str_sub(md_file, 4)
  md_links <- bind_rows(md_links, data.frame(md_year, md_file, md_link))
}

md_links %>%
  mutate(link=(md_link!="No link")) %>%
  count(md_year, link) %>%
  pivot_wider(
    id_cols=md_year, 
    names_from=link, 
    names_prefix="linked_", 
    values_from=n,
    values_fill=0) %>%
  mutate(total=linked_FALSE+linked_TRUE) %>%
  data.frame -> yr_count
yr_count %>%
  summarize(
    linked_FALSE=sum(linked_FALSE),
    linked_TRUE=sum(linked_TRUE),
    total=sum(total)) %>%
  mutate(md_year="All") %>%
  bind_rows(yr_count, .)
```

### Links found in html files

```{r html_links}
moved1 <- '<p>This page has moved to <a href="http://new.pmean.com/'
moved3 <- '<p>This page is moving to a <a href="http://new.pmean.com/'
moved4 <- '/">new website</a>.</p>'
moved2 <- '/">a new website</a>.</p>'
full_file_name <- paste0(html_path, html_files$yr, "/", html_files$fn)
html_links <- NULL
for (i_fn in full_file_name) {
  read_lines(i_fn) %>%
    str_subset(glue("({moved1}|{moved3})")) %>%
    str_replace(fixed(moved1), "") %>%
    str_replace(fixed(moved2), "") %>%
    str_replace(fixed(moved3), "") %>%
    str_replace(fixed(moved4), "") -> html_link
  html_link <- ifelse(length(html_link>0), html_link[1], "No link")
  html_file <- str_replace(i_fn, html_path, "")
  html_year <- str_sub(html_file, 1, 2)
  html_file <- str_sub(html_file, 4)
  html_links <- bind_rows(html_links, data.frame(html_year, html_file, html_link))
}
html_links %>%
  mutate(link=(html_link!="No link")) %>%
  count(html_year, link) %>%
  pivot_wider(
    id_cols=html_year, 
    names_from=link, 
    names_prefix="linked_", 
    values_from=n,
    values_fill=0) %>%
  mutate(total=linked_FALSE+linked_TRUE) %>%
  data.frame -> yr_count
yr_count %>%
  summarize(
    linked_FALSE=sum(linked_FALSE),
    linked_TRUE=sum(linked_TRUE),
    total=sum(total)) %>%
  mutate(html_year="All") %>%
  bind_rows(yr_count, .)
```

### List all linkages

```{r md-linkages}
kable(md_links)
```

```{r html-linkages}
kable(html_links)
```

```{r save_everything}
save(md_links, html_links, file="../data/linkages.RData")
```

