---
title: "Pages written in 2022"
source: new
date: "2022-12-31"
categories:
- Blog post
tags:
- Website details
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
suppressMessages(suppressWarnings(library(glue)))
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(readr)))
suppressMessages(suppressWarnings(library(stringr)))
yr <- 2023:1999
glue("[{yr}](http://new.pmean.com/{yr}/)") %>%
  paste(collapse=" | ") -> yr_list
list.files() %>%
  str_subset("md$") -> f
```

```{r}
problem_files <- NULL
date_list <- NULL
for (fn in f) {
  file_text <- read_lines(fn)
  file_text %>%
    str_subset("^source\\: ") %>%
    str_remove(fixed("source: ")) %>%
    str_remove_all('"')  %>%
    str_remove_all("'") -> file_source
  if (length(file_source)>1) {
    problem_files %<>% append(glue("{fn} has multiple sources\n"))
  }
  if (length(file_source)>0 & file_source[1]!="new") {
    problem_files %<>% 
      append(glue("{fn} has source={file_source}\n"))
  }
  file_text %>%
    str_subset(fixed("date: ")) %>%
    str_remove(fixed("date: ")) %>%
    str_remove_all('"') %>%
    str_remove_all("'")  -> file_date
  if (length(file_date)==0) {
    problem_files %<>% append(glue("{fn} has no date"))
  }
  date_list <- append(date_list, file_date[1])
}
```

```{r}
f %>%
  str_replace(fixed(".Rmd"), "") %>%
  str_replace(fixed(".md"), "") -> f
n <- length(f)
o <- order(date_list, f)
header <- glue("New website ({n} files)")
glue("+ {date_list[o]} [{f[o]}](http://new.pmean.com/{f[o]}/)  ") %>%
  paste(collapse="  \n") -> file_list
```

`r yr_list`

`r header`

`r file_list`

```{r}
if (length(problem_files)==0) {
  problem_files <- "All files passed date and source quality checks"
}
```

`r paste(problem_files, collapse="\n")`
