---
title: "Check links on new pages"
author: "Steve Simon"
date: "Created 2024-06-25"
output: html_document
---
  
This program looks for key information in the new webpages

```{r setup}
verbose <- TRUE
suppressMessages(suppressWarnings(library(glue)))
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(readr)))
suppressMessages(suppressWarnings(library(stringr)))
suppressMessages(suppressWarnings(library(tidyverse)))

load(file="../data/check_new.RData")
n_new <- nrow(new)
load(file="../data/check_old.RData")
n_old <- nrow(old)
size_limit <- 99

inc <- function(x) {
  n <- length(x)
  m <- c(FALSE, x[-1]==x[-n])
  x[m] <- " "
  x
}
test1 <- rep(letters[1:4], 1:4)
test2 <- inc(test1)
data.frame(test1, test2)
```

## pages with no links from new site to old or blog site

```{r no-link-www-1}
new %>% 
  filter(link_miss==1) %>%
  select(dir, page) -> pip1 
msg <- glue(
  "{nrow(pip1)} / {n_new} = {round(100*nrow(pip1)/n_new)}%")
```

### `r msg`

```{r no-lin-www-2}
if (verbose) {
  pip1 %>%
    mutate(dir=inc(dir)) %>%
    head(size_limit)
}
```

### pages with bad links from new site to old site

```{r bad-link-www}
old %>%
  rename(back_link=link_page) %>%
  rename(link_page=page) %>%
  rename(link_dir=dir) %>%
  select(link_dir, link_page, back_link, stub) -> mrg
new %>% 
  filter(link_miss==0) %>%
  filter(link_site=="www") %>%
  left_join(mrg, by=c("link_dir", "link_page")) %>%
  select(
    dir, 
    page, 
    link_dir, 
    link_page, 
    back_link,
    stub) -> pip1
pip1 %>%
  filter(is.na(stub)) %>%
    select(-stub) -> pip2 
msg <- glue(
  "{nrow(pip2)} / {n_new} = {round(100*nrow(pip2)/n_new)}%")
pip2 %>%
  mutate(dir=inc(dir)) %>%
  head(size_limit)
```


### pages with good links from new site to old site

```{r good-link-www}
pip1 %>%
  filter(!is.na(stub))  -> pip3 
glue("{nrow(pip3)} / {n_new} = {round(100*nrow(pip3)/n_new)}%")
pip3 %>%
  mutate(dir=inc(dir)) %>%
  head(size_limit)
```

### pages with no links from old site to new site

```{r no-link-new}
old %>% 
  filter(link_miss==1) %>%
  select(dir, page) -> pip1 
print(nrow(pip1))
pip1 %>%
  mutate(dir=inc(dir)) %>%
  head(size_limit)
```

### pages with bad links from old site to new site

```{r bad-link-new}
new %>%
  rename(back_link=link_page) %>%
  rename(link_page=page) %>%
  select(link_page, back_link, update) -> mrg

old %>%
  filter(link_miss==0) %>%
  left_join(mrg, by="link_page") %>%
  select(dir, page, link_page, update) -> pip1

pip1 %>%
  filter(is.na(update)) %>%
  select(-update)  -> pip4

print(nrow(pip4))
pip4 %>%
  mutate(dir=inc(dir)) %>%
  head(size_limit)
```


### pages with good links from old site to new site

```{r good-link-new}
pip1 %>%
  filter(!is.na(update)) -> pip5 
print(nrow(pip5))
pip5 %>%
  mutate(dir=inc(dir)) %>%
  head(size_limit)
```

