---
title: "Check links on new pages"
author: "Steve Simon"
date: "Created 2024-06-25"
execute:
  echo: false
format:
  html:
    embed-resources: true
---
  
This program looks for key information in the new webpages

```{r setup}
suppressMessages(suppressWarnings(library(glue)))
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(readr)))
suppressMessages(suppressWarnings(library(stringr)))
suppressMessages(suppressWarnings(library(tidyverse)))

new_path <- "../text/"
new_list=c("99", paste0("0", 0:9), 10:24)
save_file <- "../data/check_new.RData"
```

## Create new

```{r create}
new <- NULL
for (dir in rev(new_list)) {
  file_path <- paste0(new_path, dir)
  file_path %>%
    list.files(pattern="md$") %>%
    data.frame(dir=dir, page=.) %>%
    bind_rows(new) -> new
}
rows <- nrow(new)
new_file <-
  paste0(
  new_path, "/",
  new$dir, "/",
  new$page)
```

## Search for links to old files

```{r links}
search_link <- function(tx) {
  f_text <- "\\[sim1\\]\\: "
  tx %>%
    str_subset(f_text) %>%
    str_replace(f_text, "") %>%
    paste0("") %>%
    paste0(collapse=", ")
}
```

## Search for page_update values

```{r update}
search_stat <- function(tx) {
  c_text <- "page_update: "
  tx %>%
    str_subset(fixed(c_text)) %>%
    str_replace(fixed(c_text), "")  %>%
    paste0("") %>%
    paste0(collapse=", ")
}
```

## Search for size

```{r size}
search_size <- function(tx) {
  length(tx)
}
```

## Read file text

```{r read}
new$ext  <- str_remove(new$page, ".*\\.")
new$page <- str_remove(new$page, "\\..*")

new$update <- "999"
new$link_full <- "999"
new$size <- -1
for (i in 1:rows) {
  tx <- read_lines(new_file[i])
  new$update[i] <- search_stat(tx)
  new$link_full[i] <- search_link(tx)
  new$size[i] <- search_size(tx)
}
```

## Modify variables

```{r modify}
new$link_miss <- as.numeric(nchar(new$link_full) == 0)
new$link_full %>%
  str_remove("http://") %>%
  str_remove("\\..*") -> new$link_site
new$link_full %>%
  str_remove(".*\\.") -> new$link_ext
new$link_ext[new$link_site=="blog"] <- "/"
new$link_full %>%
  str_remove("http://www.pmean.com/") %>%
  str_remove("\\..*") %>%
  str_remove("/.*") -> new$link_dir
new$link_dir[new$link_site=="blog"] <- "/"
new$link_full %>%
  str_remove(".*/") %>%
  str_remove("\\..*") -> new$link_page
```

## Save results

```{r save}
new %>%
  select(
    dir, 
    page, 
    ext, 
    size,
    update,
    link_miss,
    link_dir,
    link_site,
    link_page,
    link_ext) %>%
  arrange(dir, page) -> new

save(new, file=save_file)
```

## Simple statistics

```{r simple}
summary(new$size)
count(new, ext)
count(new, update)
count(new, link_miss)
count(new, link_site)
count(new, link_ext)
count(new, link_dir)
```
