---
title: "Count pages completed in each year"
author: "Steve Simon"
date: "Created 2024-06-16"
output: html_document
---

### Setup

```{r setup, echo=TRUE}
knitr::opts_chunk$set(echo=TRUE)
suppressMessages(suppressWarnings(library(glue)))
suppressMessages(suppressWarnings(library(knitr)))
suppressMessages(suppressWarnings(library(lubridate)))
suppressMessages(suppressWarnings(library(tidyverse)))
md_path <- "../text/"
subdir_list=c("99", paste0("0", 0:9), 10:24)
save_file <- "../data/page_update_check.RData"
```

### create md_files

```{r create, eval=FALSE}
md_files <- NULL
for (yr in rev(subdir_list)) {
  file_path <- paste0(md_path, yr)
  file_path %>%
    list.files(pattern="md$") %>%
    data.frame(yr=yr, fn=.) %>%
    bind_rows(md_files) -> md_files
}
c_text <- "page_update: "
f_text <- "\\[sim1\\]\\: "
md_files$page_update_line <- "999"
md_files$old_link <- "999"
for (i_row in 1:nrow(md_files)) {
  full_file_name <- glue("{md_path}/{md_files$yr[i_row]}/{md_files$fn[i_row]}")
  read_lines(full_file_name) -> file_text
  file_text %>%
    str_subset(fixed(c_text)) %>%
    str_replace(fixed(c_text), "") -> page_update
  file_text %>%
    str_subset(f_text) %>%
    str_replace(f_text, "") %>%
    paste0("", collapse=", ") -> old_link
  n <- length(page_update)
  if (n > 1) {
    cat(
      glue(
        "\n\n{n} duplicates found in {full_file_name}.\n\n"))}
  page_update %>%
    paste0("", collapse=", ") -> md_files$page_update_line[i_row]
  md_files$old_link[i_row] <- old_link
}
save(md_files, file=save_file)
```

```{r}
load(file=save_file)
```

### List duplicates

```{r list-duplicates}
md_files %>%
  group_by(fn) %>%
  mutate(n=n()) %>%
  filter(n>1) %>%
  select(-n) %>%
  arrange(fn, yr) %>%
  data.frame -> piper
if (nrow(piper) > 0) piper
if (nrow(piper) == 0) "None found"
```

### Count page_update fields

```{r md_links}
count(md_files, page_update_line)
```

```{r}
for (y in subdir_list) {
  md_files %>%
    filter(yr==y) %>%
    count(yr, page_update_line) %>%
    print
  cat("\n\n")
}
```

### Pages with page_update = `r (update_text="no")`

```{r}
md_files %>%
  filter(page_update_line==update_text) %>%
  select(-old_link) -> piper
if (nrow(piper) > 0) piper
if (nrow(piper) == 0) "None found"
```

### Pages with page_update = `r (update_text="partial")`

```{r}
md_files %>%
  filter(page_update_line==update_text) %>%
  select(-old_link) -> piper
if (nrow(piper) > 0) piper
if (nrow(piper) == 0) "None found"
```

### Pages with page_update = `r (update_text="complete")`

```{r}
md_files %>%
  filter(page_update_line==update_text) %>%
  select(-old_link)
```

### Pages with page_update = `r (update_text="")`

```{r}
md_files %>%
  filter(page_update_line==update_text) %>%
  select(-old_link) -> piper
if (nrow(piper) > 0) piper
if (nrow(piper) == 0) "None found"
```

### Pages with links to previous site

```{r}
md_files %>%
  filter(nchar(old_link) > 0) %>%
  glue_data("-   [{fn}]({old_link})\n") -> linked
```

`r paste0(linked, collapse="\n")`

### Pages without links to previous site

```{r}
md_files %>%
  filter(nchar(old_link) == 0) %>%
  select(yr, fn, old_link) -> piper
if (nrow(piper) > 0) piper
if (nrow(piper) == 0) "None found"
```

```{r}
test1 <- paste0("## ", 1:5, collapse="\n\n")
```

`r test1`

```{r}
#| results: asis
cat(r'(
# Header

Text
)')
```

```{r}
#| results: asis
cat(r'(\n# Header\n\nText]\n)')
```

