---
title: "Pages written in a given year"
source: new
date: "2023-01-10"
categories:
- Blog post
tags:
- Website details
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
suppressMessages(suppressWarnings(library(glue)))
suppressMessages(suppressWarnings(library(magrittr)))
suppressMessages(suppressWarnings(library(readr)))
suppressMessages(suppressWarnings(library(stringr)))
```

```{r}
write_yaml <- function(page_year) {
  century <- ifelse(page_year==99, 19, 20)
  output_text <- glue('
  ---
  title: "Pages written in {century}{page_year}"
  source: new
  date: {century}{page_year}-12-31
  categories:
  - Blog post
  tags:
  - Website details
  output: html_document
  ---')
  return(output_text)
}
```

```{r}
write_links <- function(yr_list) {
  glue("[{yr_list}](http://new.pmean.com/{yr_list}/)") %>%
    paste(collapse=" | ")
}
```

```{r}
check_source <- function(file_text) {
  file_text %>%
    str_subset("^source\\: ") %>%
    str_remove(fixed("source: ")) %>%
    str_remove_all('"')  %>%
    str_remove_all("'") -> file_source
  
  if (length(file_source)==0) return("Error: no source")

  if (length(file_source)>1) return("Error: multiple sources")

  return(file_source)
}
```

```{r}
check_dates <- function(file_text) {
  file_text %>%
    str_subset("^date\\: ") %>%
    str_remove(fixed("date: ")) %>%
    str_remove_all('"') %>%
    str_remove_all("'")  -> file_date
  if (length(file_date)==0) return("Error: no date")
  if (length(file_date)>1) return("Error: multiple dates")
  return(file_date)
}
```

```{r}
write_list <- function(page_year) {
  # get file list
  list.files(path=glue("../text/{page_year}", pattern="*.md")) %>%
    str_subset("md$") -> f
  # open files and find information
  source_list <- NULL
  date_list <- NULL
  for (fn in f) {
    file_text <- read_lines(glue("../text/{page_year}/{fn}"))
    # get source
    source_list <- append(
      source_list,
      check_source(file_text))
    #get dates
    date_list <- append(
      date_list,
      check_dates(file_text))
  }
  # strip extensions
  f %>%
    str_replace(fixed(".Rmd"), "") %>%
    str_replace(fixed(".md"), "") -> f
  n <- length(f)
  # search for problem files
  bad_date <- str_detect(date_list, "Error")
  bad_source <- str_detect(source_list, "Error")
  old_source <- (!str_detect(source_list, "new")) & (!bad_source)
  old_link <- glue("Link to earlier page [here]({source_list}).")
  old_link[!old_source] <- ""
  # create RMarkdown text
  links <- glue(
    "+ {date_list} ",
    "[{f}]",
    "(http://new.pmean.com/{f}/). {old_link}  ")
  # store in a sorted data frame
  o <- order(date_list, f)
  return(
    data.frame(
      f, 
      links,
      date_list,
      source_list,
      bad_date,
      bad_source)[o, ])
}
```

```{r}
for (four_digit_year in c("2000")) {
  two_digit_year <- str_sub(four_digit_year, 3, 4)
  yaml_text <- write_yaml(two_digit_year)
  l <- write_list(two_digit_year)
  n <- dim(l)[1]
  fn <- glue("../text/{two_digit_year}/{four_digit_year}.md")
  write_lines(
    yaml_text, 
    file=fn,
    append=FALSE)
  write_lines(
    glue("New website ({n} files)\n\n"),
    file=fn,
    append=TRUE)
  write_lines(
    l$links, 
    file=fn,
    append=TRUE)
  problem_files <- c(
    paste(l$f, l$date_list)[l$bad_date],
    paste(l$f, l$source_list)[l$bad_source])
  all_good <- "All files passed date and source quality checks"
  if (length(problem_files)==0) problem_files <- all_good
  write_lines(
    "\n\n### Quality check\n",
    file=fn,
    append=TRUE)
  write_lines(
    paste0("+ ", problem_files),
    file=fn,
    append=TRUE)
}
```

Links created for `r dim(l)[1]` pages in `r four_digit_year`.

`r paste(paste("1.", problem_files), collapse="\n")`

`r l$source_list`
